source 'https://rubygems.org'

ruby '2.2.0'

gem 'rails'
gem 'kaminari'
gem 'nokogiri'
gem 'aws-sdk'
gem 'puma'
gem 'pg'
gem 'turbolinks'
gem 'httparty'
gem 'rails_12factor'
gem 'active_model_serializers', '~> 0.8.3'
gem 'pry'
gem 'pry-remote'
gem 'pry-stack_explorer'
gem 'pry-byebug'
gem 'elasticsearch-model'
gem 'elasticsearch-rails'
gem 'redcarpet'