source 'https://rubygems.org'

ruby '2.3.1'

gem 'rails'
gem 'kaminari'
gem 'nokogiri'
gem 'aws-sdk'
gem 'puma'
gem 'pg'
gem 'httparty'
gem 'rails_12factor'
gem 'active_model_serializers', '~> 0.8.3'
gem 'pry-rails'
gem 'pry-byebug'
gem 'elasticsearch-model'
gem 'elasticsearch-rails'
gem 'redcarpet'
