development:
  adapter: postgresql
  database: thisamericanlifeco_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: thisamericanlifeco_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: thisamericanlifeco_production
  pool: 5
  timeout: 5000
